FROM postgres:16

# Instalar y generar el locale es_ES.UTF-8
RUN apt-get update && apt-get install -y locales \
 && sed -i 's/# *es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen \
 && locale-gen es_ES.UTF-8 \
 && update-locale LANG=es_ES.UTF-8 LC_ALL=es_ES.UTF-8 \
 && rm -rf /var/lib/apt/lists/*

ENV LANG=es_ES.UTF-8 \
    LC_ALL=es_ES.UTF-8
