services:
  postgres:
    image: postgres:16
    container_name: pg_airflow16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata_airflow:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro

  # Inicialización de Airflow (una sola vez)
  airflow-init:
    image: apache/airflow:3.1.0-python3.11
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      # Habilitar FAB y asegurar que el provider esté disponible
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-fab"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./scripts:/opt/bootstrap:ro
    command: >
      bash -eo pipefail -lc 'bash /opt/bootstrap/create_admin.sh'
    restart: "no"

  airflow:
    image: apache/airflow:3.1.0-python3.11
    container_name: airflow_3_1_py311
    hostname: airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5439/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      S3_BUCKET: ${S3_BUCKET}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -eo pipefail -lc "
      mkdir -p dags logs plugins;
      airflow db check;
      airflow scheduler & airflow dag-processor & exec airflow api-server --port 8080
      "

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    env_file: .env
    entrypoint: >
      /bin/sh -c "
      echo 'Configurando MinIO...';
      /usr/bin/mc alias set myminio http://minio:9001 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      echo 'Reseteando la configuración OpenID de MinIO...';
      /usr/bin/mc admin config reset myminio identity_openid;
      echo 'Creando el bucket S3 si no existe...';
      /usr/bin/mc mb --ignore-existing myminio/${S3_BUCKET};
      echo 'Inicialización de MinIO completada.';
      "
    restart: "no"

  minio:
    image: minio/minio:latest
    container_name: minio_airflow
    ports:
      - "9001:9001"
      - "9101:9101"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9101"
    volumes:
      - ./data:/data

volumes:
  pgdata_airflow:
    name: pgdata_airflow
