services:
  postgres:
    image: postgres:16
    container_name: pg_airflow16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro

  # Inicialización de Airflow (una sola vez)
  airflow-init:
    image: apache/airflow:3.1.0-python3.11
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      # Habilitar FAB y asegurar que el provider esté disponible
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-fab"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./scripts:/opt/bootstrap:ro
    command: >
      bash -eo pipefail -lc 'bash /opt/bootstrap/create_admin.sh'
    restart: "no"

  airflow:
    image: apache/airflow:3.1.0-python3.11
    container_name: airflow_3_1_py311
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"   # mejor en prod
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-fab"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -eo pipefail -lc "
      mkdir -p dags logs plugins;
      airflow db check;
      airflow scheduler & airflow dag-processor & exec airflow api-server --port 8080
      "

volumes:
  pgdata:
    name: airflow_pgdata
